src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnimalRepository::class)
 */
class Animal
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nomScientifique;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lieuDeVie;

    /**
     * @ORM\ManyToOne(targetEntity=Famille::class, inversedBy="animals")
     * @ORM\JoinColumn(nullable=false)
     */
    private $famille;

    /**
     * @ORM\ManyToOne(targetEntity=RegimeAlimentaire::class, inversedBy="Animal")
     * @ORM\JoinColumn(nullable=false)
     */
    private $regimeAlimentaire;

    /**
     * @ORM\ManyToMany(targetEntity=Animal::class, inversedBy="predateurs")
     */
    private $predateurs;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $LienWiki;

    public function __construct()
    {
        $this->predateurs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getNomScientifique(): ?string
    {
        return $this->nomScientifique;
    }

    public function setNomScientifique(?string $nomScientifique): self
    {
        $this->nomScientifique = $nomScientifique;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getLieuDeVie(): ?string
    {
        return $this->lieuDeVie;
    }

    public function setLieuDeVie(?string $lieuDeVie): self
    {
        $this->lieuDeVie = $lieuDeVie;

        return $this;
    }

    public function getFamille(): ?Famille
    {
        return $this->famille;
    }

    public function setFamille(?Famille $famille): self
    {
        $this->famille = $famille;

        return $this;
    }

    public function getRegimeAlimentaire(): ?RegimeAlimentaire
    {
        return $this->regimeAlimentaire;
    }

    public function setRegimeAlimentaire(?RegimeAlimentaire $regimeAlimentaire): self
    {
        $this->regimeAlimentaire = $regimeAlimentaire;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getPredateurs(): Collection
    {
        return $this->predateurs;
    }

    public function addPredateur(self $predateur): self
    {
        if (!$this->predateurs->contains($predateur)) {
            $this->predateurs[] = $predateur;
        }

        return $this;
    }

    public function removePredateur(self $predateur): self
    {
        $this->predateurs->removeElement($predateur);

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getLienWiki(): ?string
    {
        return $this->LienWiki;
    }

    public function setLienWiki(?string $LienWiki): self
    {
        $this->LienWiki = $LienWiki;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getNom();
    }


}

src/Form/AnimalType.php
<?php

namespace App\Form;

use App\Entity\Animal;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnimalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('nomScientifique')
            ->add('photo')
            ->add('lieuDeVie')
            ->add('famille')
            ->add('regimeAlimentaire')
            ->add('predateurs')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Animal::class,
        ]);
    }
}

src/Controller/AnimalController.php
<?php

namespace App\Controller;

use App\Entity\Animal;
use App\Form\AnimalType;
use App\Repository\AnimalRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AnimalController extends AbstractController
{
    private $em;
    private $repo;

    public function __construct(EntityManagerInterface $entityManager, AnimalRepository $repo)
    {
        $this->em = $entityManager;
        $this->repo = $repo;
    }

    #[Route('/animal', name: 'animal')]
    public function index(): Response
    {
        return $this->render('animal/index.html.twig', [
            'controller_name' => 'AnimalController',
            'titre' => 'Les Animaux'
        ]);
    }

    #[Route('animal/ajout', name: 'animalajout')]
    public function ajout(): Response
    {
        $animal = new Animal();
        $form = $this->createForm(AnimalType::class, $animal);
        return $this->render('animal/index.html.twig', [
            'controller_name' => 'AnimalController',
            'form' => $form->createView(),
        ]);
    }

    #[Route('animal/{nom}', name: ('showAnimal'))]
    public function showAnimal(Request $request, $nom): Response
    {
        $animal = $this->repo->findOneBy(['nom' => $nom]);


        //$predateurs = $this->repo->getPredateurs($animal);
        // dump($predateurs);

        return $this->render('animal/show.html.twig', [
            'controller_name' => 'AnimalController',
            'animal' => $animal,
            //'predateurs' => $predateurs,
            'titre' => $animal->getNom(),
        ]);
    }
}

templates/animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SdM2021 @Brest - {{ titre }}{% endblock %}

{% block body %}
    {% block content %}
    {% endblock %}
{% endblock %}

templates/animal/show.html.twig
{% extends 'base.html.twig' %}
{% block title %}SdM2021 @Brest - {{ titre }}{% endblock %}

{% block body %}
{#    <style>#}
{#        .example-wrapper {#}
{#            margin: 1em auto;#}
{#            max-width: 800px;#}
{#            width: 95%;#}
{#            font: 18px/1.5 sans-serif;#}
{#        }#}

{#        .example-wrapper code {#}
{#            background: #F5F5F5;#}
{#            padding: 2px 6px;#}
{#        }#}
{#    </style>#}
    {% block navBar %}{% endblock %}
    {% block content %}
        {# {{ form(form) }} #}

        {# {{ form(form) }} #}
        <div class="container ">
            <div class="row animal">
                <div class="col-12 col-sm-4">
                    <img class="photo " src="{{ asset('assets/img/animaux/' ~ animal.photo) }}"
                         alt="La photo : {{ animal.nom }}">
                </div>
                <div class="col-12 col-sm-4">
                    <div class="mb-4"><span class="h2">{{ animal.nom }}</span> <span
                                class="font-italic">({{ animal.nomScientifique }})</span></div>
                    <div class="mb-4">
                        <span class="mb-4 font-weight-bold">Régime alimentaire : </span>
                        <span>{{ animal.regimeAlimentaire }}</span>
                    </div>
                    <div class="mb-4">
                        <span class="mb-4 font-weight-bold">Lieu de vie : </span>
                        <span>{{ animal.lieuDeVie }}</span>
                    </div>
                    <div class="mb-4">
                        {{ animal.description }}
                    </div>
                    <div>
                        <a class="navajowhite " href="{{ animal.lienWiki }}"> {{ animal.lienWiki }}</a>
                    </div>
                </div>
                {# {{ animal.photo }} #}
                {# {{ animal.nom }} #}

{#                <div id="carouselExampleControls" class="carousel slide bg-danger z-depth-1-half" data-ride="carousel">#}
{#                    <div class="carousel-inner">#}
{#                        <div class="carousel-item active">#}
{#                            <img class="d-block w-100" src="..." alt="First slide">#}
{#                        </div>#}
{#                        <div class="carousel-item">#}
{#                            <img class="d-block w-100" src="..." alt="Second slide">#}
{#                        </div>#}
{#                        <div class="carousel-item">#}
{#                            <img class="d-block w-100" src="..." alt="Third slide">#}
{#                        </div>#}
{#                    </div>#}
{#                    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">#}
{#                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>#}
{#                        <span class="sr-only">Previous</span>#}
{#                    </a>#}
{#                    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">#}
{#                        <span class="carousel-control-next-icon" aria-hidden="true"></span>#}
{#                        <span class="sr-only">Next</span>#}
{#                    </a>#}
{#                </div>#}
            </div>

        </div>


    {% endblock %}
{% endblock %}